<!-- webGUI SDS Logging : Requires bootstrap && lastlog file parsed-->

<!DOCTYPE html>
<html lang="en">
<head>
  <title>SDS Log Viewer</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
  <h2>SDS Logging System</h2>
  <p>Same folder of 'lastlog' file generated by ./SDS.py -showlogs</p>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Destination</th>
        <th>Source</th>
        <th>Source Port</th>
        <th>Destination Port</th>
        <th>Protocol</th>
        <th>TTL</th>
        <th>Time</th>
      </tr>
    </thead>


    <tbody>
        <?php
$handle = fopen("lastlog", "r"); //logging file from logging parser
if ($handle) {
    while (($line = fgets($handle)) !== false) {
        $rawdata=explode("SDSIN",$line);
        $rawdata0=explode(" ",$rawdata[0]);
        $rawdata=$rawdata[1];
        $rawdata=explode(" ",$rawdata);
//      print_r($rawdata0);
        $dst=str_replace("DST="," ",$rawdata[7]);
        $src=str_replace("SRC="," ",$rawdata[6]);
        $srcp=str_replace("SPT="," ",$rawdata[20]);
        $dstp=str_replace("DPT="," ",$rawdata[21]);
        $dport=(int)$dstp;
        $warning=" ";
        if(($dport>=1024) && ( $dport <=65535 )) { $warning='class="danger"';} //make colored rows
        elseif($dport==443) { $warning='class="info"';}
        elseif($dport==80) { $warning='class="success"';}
        $proto=str_replace("PROTO="," ",$rawdata[19]);
        $ttl=str_replace("TTL="," ",$rawdata[14]);
        $time=$rawdata0[1]." ".$rawdata0[0]." ".$rawdata0[2];


        //if(strpos($rawdata0,"ERR")!== false){ $warning='class="danger"'; echo "Err";}
        echo "<tr ".$warning."><td>".$dst."</td>";
        echo "<td>".$src."</td>";
        echo "<td>".$srcp;
        echo "<td>".$dstp;
        echo "<td>".$proto;
        echo "<td>".$ttl;
        echo "<td>".$time;
}
    fclose($handle);
} else {echo "error";} ?>
</td>


      </tr>


    </tbody>
  </table>
</div>

</body>
</html>
